### PR TITLE
create the gluster cluster from a setup vm

### PR DESCRIPTION
**Pull request by obnoxxx**
This PR untangles the setup of the gluster cluster from the vagrant provisioning. Here is what is changed more specifically.
- Vagrant is now mainly used to spin up the vms and create an inventory file for ansible.
- A setup VM is created and prepared with the necessary packages etc.
- Inventory and ssh-key files are generated and ansible roles and playbooks are copied to the setup vm.
- The playbooks for configuring the gluster nodes and setting up the gluster cluster are executed from the setup vm.
- The various commands can be invoked by makefile targets.
-Finally, this PR adds the setup of the vms to `make test` so that this will be tested from here on in each PR.

The motivations of doing this are:
* Make the test environment more self-contained with less dependencies on the host it is running on.
* Make it possible more easily to run various parts of the ansible playbooks independently of vagrant provisioning. This way, they will be more re-usable.

### CODE REVIEW

**Comment by obnoxxx** [comment]
Questionable aspect: Is it a good idea to use ansible to invoke ansible on the remote setup machine?

**Comment by spuiuk** [comment]
Have you seen ansible_local?
https://www.vagrantup.com/docs/provisioning/ansible_local.html

Any reason you do not want to invoke ansible on the host machine?

Sachin Prabhu

**Comment by obnoxxx** [comment]
@spuiuk wrote:
> Have you seen ansible_local?
> https://www.vagrantup.com/docs/provisioning/ansible_local.html

Yes, but this is for vagrant specifically. Not sure if ansible proper has something like this.
One purpose of the PR is to use vagrant for less. Have more re-usable ansible roles and playbooks that can be called independently.

> Any reason you do not want to invoke ansible on the host machine?

See the (updated) description of the PR: I want to have less requirements on the host machine. Also don't want to require the user of this to have to install additional software (like the gluster-ansible copr) on the host machine. This way, the whole setup is more self-contained. Btw, this matches pretty much with the motivation of "ansible_local" you mentioned.

**Comment by obnoxxx** [comment]
BTW: 
* I am running ansible on the host machine, just not to run gluster-ansible. But for prep tasks.
* I was wondering how good an idea it is to invoke ansible with ansible because the output of the second layer ansible is completely clobbered. In order to be able to manually invoke ansible on the setup machine, I have added make targets in the ansible directory.

**Comment by spuiuk** [comment]
Sounds like Ansible-ception.

/me is sure to get nightmares now.

**Comment by obnoxxx** [comment]
> Sounds like Ansible-ception.

Not 100% sure what that means.

> /me is sure to get nightmares now.

Please don't! :-)

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
Strange error in test execution.
https://ci.centos.org/view/Gluster/job/gluster_samba-integration/26/console

Everything seems to work fine until adding the gluster nightly repos:

```
PLAY [cluster] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [storage1]
ok: [storage0]

TASK [node.setup : Perform a complete update] **********************************
changed: [storage1]
changed: [storage0]

TASK [node.setup : Enable EPEL repository] *************************************
changed: [storage0]
changed: [storage1]

TASK [node.setup : Enable GlusterFS nightly rpms repository] *******************
fatal: [storage1]: FAILED! => {
"changed": true,
"cmd": ["yum-config-manager", "--add-repo", "https://ci.centos.org/artifacts/gluster/nightly/master.repo"],
"delta": "0:00:00.554471",
"end": "2020-03-24 01:44:20.558059",
"msg": "non-zero return code",
"rc": 1,
"start": "2020-03-24 01:44:20.003588",
"stderr": "",
"stderr_lines": [],
"stdout": "Loaded plugins: fastestmirror\nadding repo from: https://ci.centos.org/artifacts/gluster/nightly/master.repo\ngrabbing file https://ci.centos.org/artifacts/gluster/nightly/master.repo to /etc/yum.repos.d/master.repo\nCould not fetch/save url https://ci.centos.org/artifacts/gluster/nightly/master.repo to file /etc/yum.repos.d/master.repo: [Errno 14] HTTPS Error 404 - Not Found", "stdout_lines": [
  "Loaded plugins: fastestmirror",
  "adding repo from: https://ci.centos.org/artifacts/gluster/nightly/master.repo",
  "grabbing file https://ci.centos.org/artifacts/gluster/nightly/master.repo to /etc/yum.repos.d/master.repo",
  "Could not fetch/save url https://ci.centos.org/artifacts/gluster/nightly/master.repo to file /etc/yum.repos.d/master.repo: [Errno 14] HTTPS Error 404 - Not Found"
]
}
fatal: [storage0]: FAILED! => {
...
```

Can the setup node not reach outside? But yum update etc worked!

**Comment by obnoxxx** [comment]
@nixpanic any idea what's going wrong here on the VM reaching the gluster nightly repo url?

**Comment by nixpanic** [comment]
On Tue, Mar 24, 2020 at 02:32:44AM -0700, Michael Adam wrote:
> @nixpanic any idea what's going wrong here on the VM reaching the gluster nightly repo url?

I think https://github.com/gluster/samba-integration/pull/17 could fix
it.

**Comment by obnoxxx** [comment]
rebased

**Comment by obnoxxx** [comment]
It failed again: https://ci.centos.org/view/Gluster/job/gluster_samba-integration/30/consoleFull

```
fatal: [storage0]: FAILED! => {
  "changed": false,
  "msg": "error running gluster (/sbin/gluster --mode=script peer probe storage1) command (rc=1): peer probe: failed: Probe returned with Transport endpoint is not connected\n"
}

NO MORE HOSTS LEFT 
```

**Comment by nixpanic** [comment]
On Tue, Mar 24, 2020 at 05:15:05AM -0700, Michael Adam wrote:
> It failed again: https://ci.centos.org/view/Gluster/job/gluster_samba-integration/30/consoleFull
> 
> ```
> fatal: [storage0]: FAILED! => {
>   "changed": false,
>   "msg": "error running gluster (/sbin/gluster --mode=script peer probe storage1) command (rc=1): peer probe: failed: Probe returned with Transport endpoint is not connected\n"
> }
> 
> NO MORE HOSTS LEFT 
> ```

Make sure the VMs can resolve the hostnames?

**Comment by obnoxxx** [comment]
added a test whether the nodes can ping each other by name

**Comment by obnoxxx** [comment]
And it's proven: it is name resolution:

```
ping: storage0: Name or service not known
```
https://ci.centos.org/view/Gluster/job/gluster_samba-integration/31/console

**Comment by spuiuk** [comment]
You probably need the hostmanager plugin.
https://github.com/devopsgroup-io/vagrant-hostmanager

**Comment by spuiuk** [comment]
Just realised that I am now hitting the same issue. This was working until recently. The only thing I did was update packages and reboot.

**Comment by obnoxxx** [comment]
@spuiuk wrote:
> Just realised that I am now hitting the same issue. This was working until recently. The only thing I did was update packages and reboot.

Which issue? That dns resolution of the vms does not work on the vms themselves?

**Comment by spuiuk** [comment]
dns.

**Comment by obnoxxx** [comment]
added some tests to start debugging this via ci runs... print dnsmasq processes on host. and print resolv.conf in the setup vm

**Comment by obnoxxx** [comment]
more test output (some can be temporary....)

**Comment by obnoxxx** [comment]
resolv.conf on the guest (setup) looks ok:
```
23:30:26 TASK [setup.test : content of /etc/resolv.conf] ********************************
23:30:26 ok: [setup] => {
23:30:26     "resolv_conf_contents.stdout_lines": [
23:30:26         "# Generated by NetworkManager", 
23:30:26         "nameserver 192.168.121.1"
23:30:26     ]
23:30:26 }
```

dnsmasq processes on the host seem to be there:
```
23:24:29 TASK [local.test : print dnsmasq processes] ************************************
23:24:29 ok: [localhost] => {
23:24:29     "ps_output.stdout_lines": [
23:24:29         "nobody   20858  0.0  0.0  53896  1072 ?        S    22:23   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper", 
23:24:29         "root     20859  0.0  0.0  53868   556 ?        S    22:23   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper", 
23:24:29         "nobody   28846  0.0  0.0  53896  1076 ?        S    22:23   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/vagrant-libvirt.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper", 
23:24:29         "root     28847  0.0  0.0  53868   560 ?        S    22:23   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/vagrant-libvirt.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper", 
23:24:29         "root     29944  0.0  0.0 113188  1204 ?        S    22:24   0:00 /bin/sh -c ps axu | grep dnsmasq", 
23:24:29         "root     29946  0.0  0.0 112720   944 ?        S    22:24   0:00 grep dnsmasq"
23:24:29     ]
23:24:29 }
```

The next run should show dump of the vagrant-libvirt net-config from libvirt and hostname output on the nodes.

**Comment by obnoxxx** [comment]
vagrant-libvirt net looks ok (just like here locally):
```
23:54:24 TASK [local.test : print vagrant-libvirt definition] ***************************
23:54:24 ok: [localhost] => {
23:54:24     "output.stdout_lines": [
23:54:24         "<network connections='3' ipv6='yes'>", 
23:54:24         "  <name>vagrant-libvirt</name>", 
23:54:24         "  <uuid>551e4505-3a9e-4a6e-a813-eaff5e7d36f9</uuid>", 
23:54:24         "  <forward mode='nat'>", 
23:54:24         "    <nat>", 
23:54:24         "      <port start='1024' end='65535'/>", 
23:54:24         "    </nat>", 
23:54:24         "  </forward>", 
23:54:24         "  <bridge name='virbr1' stp='on' delay='0'/>", 
23:54:24         "  <mac address='52:54:00:fb:78:21'/>", 
23:54:24         "  <ip address='192.168.121.1' netmask='255.255.255.0'>", 
23:54:24         "    <dhcp>", 
23:54:24         "      <range start='192.168.121.1' end='192.168.121.254'/>", 
23:54:24         "    </dhcp>", 
23:54:24         "  </ip>", 
23:54:24         "</network>"
23:54:24     ]
23:54:24 }
```

**Comment by obnoxxx** [comment]
I had changed the cluster-vars to use IP addresses to avoid the problem with dns resolution in peer probe. But now it seems to fail even earlier. Strange:

```
"TASK [gluster.cluster/roles/gluster_volume : Start glusterd on the nodes if not already started] ***",
"failed: [storage0] (item=192.168.122.100) => {
\"ansible_loop_var\": \"item\",
\"item\": \"192.168.122.100\",
\"msg\": \"Failed to connect to the host via ssh: Warning: Permanently added '192.168.122.100' (ECDSA) to the list of known hosts.\\r\\n
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\",
\"unreachable\": true
}",
"failed: [storage0] (item=192.168.122.101) => {
\"ansible_loop_var\": \"item\",
\"item\": \"192.168.122.101\",
\"msg\": \"Failed to connect to the host via ssh: Warning: Permanently added '192.168.122.101' (ECDSA) to the list of known hosts.\\r\\n
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\",
\"unreachable\": true
}",
"fatal: [storage0]: UNREACHABLE! => {
\"changed\": false,
\"msg\": \"All items completed\",
\"results\": [
{
\"ansible_loop_var\": \"item\",
\"item\": \"192.168.122.100\",
\"msg\": \"Failed to connect to the host via ssh: Warning: Permanently added '192.168.122.100' (ECDSA) to the list of known hosts.\\r\\n
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\",
\"unreachable\": true
},
{
\"ansible_loop_var\": \"item\",
\"item\": \"192.168.122.101\",
\"msg\": \"Failed to connect to the host via ssh: Warning: Permanently added '192.168.122.101' (ECDSA) to the list of known hosts.\\r\\n
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\",
\"unreachable\": true
}
]
}", "", "NO MORE HOSTS LEFT 
```

**Comment by obnoxxx** [comment]
Why is gluster-ansible trying to ssh into the nodes by the IP addresses from the cluster-vars file and not via the ips from the inventory?

**Comment by nixpanic** [comment]
On Wed, Mar 25, 2020 at 05:21:58AM -0700, Michael Adam wrote:
> Why is gluster-ansible trying to ssh into the nodes by the IP addresses from the cluster-vars file and not via the ips from the inventory?

Do they IPs resolve to different hostnames?

**Comment by obnoxxx** [comment]
@nixpanic wrote:
> Do they IPs resolve to different hostnames?
I don't think the IPs resolve to anything.

But OH!!!
If it is the setup machine which needs to do this: the setup machine is not on the network with those addresses. Only on the vagrant network... But *WHY* would the gluster-ansible try to ssh to those IP addresses?

**Comment by obnoxxx** [comment]
I got it: it happens due to

https://github.com/gluster/gluster-ansible-cluster/blob/master/roles/gluster_volume/tasks/main.yml#L7

```
- name: Start glusterd on the nodes if not already started
  service:
       state: started
       name: glusterd
       enabled: yes
  delegate_to: "{{ item }}"
  run_once: true
  with_items: "{{ gluster_cluster_hosts }}"
```

**Comment by obnoxxx** [comment]
So basically, gluster-ansible(-infra) assumes that the the ansible connection to the gluster nodes is done through the same IPs/interfaces that the nodes are using for peer probe. I don't think that this is a good thing necessarily. 

This is also reflected in the default/example `cluster-vars.yml` file here: https://github.com/gluster/gluster-ansible/blob/master/playbooks/gluster-cluster/cluster-vars.yml#L65

```
# Variable for creating a GlusterFS volume
# groups['all'] tells to use the hosts mentioned in the inventory files to be
# used in the cluster. If only a subset has to be used change the `all' to the
# name of the section

gluster_cluster_hosts: "{{ groups['all'] }}"
```

**Comment by obnoxxx** [comment]
Added the setup machine to the private cluster network.

**Comment by obnoxxx** [comment]
Same error with the IP/nic added to the setup VM.

**Comment by obnoxxx** [comment]
I think the nodes/IPs *need* to be in the inventory.... Ansible will just not know how to connect if it is not in the inventory.

I could revert to host names and prepare a .ssh/config file...

**Comment by obnoxxx** [comment]
reworked it a bit again to use host names and prepare ssh config. works on my machine now.

**Comment by obnoxxx** [comment]
forgot to disable ping by name test...
i might still need to add a hosts file :-(

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
dang, forgot one instance of the ping test...

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
retest this please

https://ci.centos.org/view/Gluster/job/gluster_samba-integration/42/console again had a weird setup issue

**Comment by obnoxxx** [comment]
Again failure to start vm

```
Call to virDomainCreateWithFlags failed: the CPU is incompatible with host CPU: Host CPU does not provide required features: svm"
```

bad host.

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
I just found this again: https://github.com/heketi/heketi/pull/1008
We fixed this (worked around this) in heketi before...
Applying the same fix to our vagrant file. But I will let the current run (which luckily started VMs..) complete first before pushing over.

**Comment by obnoxxx** [comment]
Now we are back to peer probe, full circle...

ansible ssh from setup to hosts via name works again, now that the host names are used again and the names are in the inventory.

But peer probe fails, I guess because of lack of name resolution.
Maybe I need to install a hosts file after all. But it would be really ugly... :-/

**Comment by obnoxxx** [comment]
@spuiuk @nixpanic - it passed! :-)

**Comment by obnoxxx** [comment]
FYI: the `/etc/hosts` file solved it. I hard-coded it to get us unblocked. We should generate it along with the nodes list in the `cluster-vars.yml`

**Comment by nixpanic** [comment]
On Wed, Mar 25, 2020 at 12:58:06PM -0700, Michael Adam wrote:
> Now we are back to peer probe, full circle...
> 
> ansible ssh from setup to hosts via name works again, now that the host names are used again and the names are in the inventory.
> 
> But peer probe fails, I guess because of lack of name resolution.
> Maybe I need to install a hosts file after all. But it would be really ugly... :-/

For many things you probably need working DNS (or fake it with
/etc/hosts). I agree that /etc/hosts is ugly, but it might be sufficient
for now. Just file an issue to check/configure dnsmasq correctly and
come back to it later.

**Pull request merged**
