### PR TITLE
Disable intervention of gluster-ansible-features in setting up CTDB

### PR DESCRIPTION
**Pull request by anoopcs9**

### CODE REVIEW

**Comment by spuiuk** [comment]
Also once you have it running on your test system, can you run it twice to see if this fixes the problem with multiple make commands.

**Comment by anoopcs9** [comment]
> Also once you have it running on your test system, can you run it twice to see if this fixes the problem with multiple make commands.

Ok. I will check.

**Comment by anoopcs9** [comment]
> Also once you have it running on your test system, can you run it twice to see if this fixes the problem with multiple make commands.

Here it is:
As expected the only problem is that we don't have our GlusterFS volume share section inside smb.conf because of blind copying of _smb.conf_(overwriting old one from first run) which results in  following _smb.conf_:
```
[global]
netbios name = GLUSTERTEST
clustering = yes
log file = /var/log/samba/log.%m
max log size = 0
server string = Samba server version %v
workgroup = MYGROUP
security = user

kernel share modes = No
map archive = No
posix locking = No
kernel change notify = no

load printers = no
printcap name = /dev/null
disable spoolss = yes
printing = bsd
show add printer wizard = no
vfs objects = acl_xattr glusterfs
```
So we can get rid of _user.smb_ volume set option and go with one of the following options:
- use _include_ parameter to define our volume share section
- insert entire volume share section in `samba-glusterfs.setup` role

**Comment by anoopcs9** [comment]
@spuiuk @obnoxxx 
I can confirm successful `make test` run second time with changes associated with this PR.

**Comment by spuiuk** [comment]
I have applied the "Do not Merge" label on this PR because we cannot include it until the corresponding PR in gluster-ansible is included and new rpms are created for use in our cluster.

**Review by obnoxxx — DISMISSED** [review]
This is fantastic! Thanks @anoopcs9 !

If I understand it correctly, we could separate the change for not setting `user.smb` from the ctdb volume test into a separate commit and possibly already raise it in a separate PR, righ?

**Comment by anoopcs9** [comment]
> This is fantastic! Thanks @anoopcs9 !
> 
> If I understand it correctly, we could separate the change for not setting `user.smb` from the ctdb volume test into a separate commit and possibly already raise it in a separate PR, righ?

Yes. I will raise another PR.

**Comment by anoopcs9** [comment]
> This is fantastic! Thanks @anoopcs9 !
> 
> If I understand it correctly, we could separate the change for not setting `user.smb` from the ctdb volume test into a separate commit and possibly already raise it in a separate PR, righ?

Changes have been separated out and we now have _gluster-ansible-features_ build available with option to disable setting up of CTDB using a boolean `gluster_features_ctdb_enable_hook_scripts`

**Review by spuiuk — APPROVED** [review]
Looks good.

**Pull request merged**
