### PR TITLE
Add GlusterFS nightly build repository during rpm install test

### PR DESCRIPTION
**Pull request by anoopcs9**

### CODE REVIEW

**Comment by anoopcs9** [comment]
CI failure will be fixed when nightly GlusterFS builds are available with the [patch](https://review.gluster.org/#/c/glusterfs/+/24563/) for adding necessary `Provides:` with _libgfapi0_ sub-package.

**Comment by anoopcs9** [comment]
retest this please

**Comment by anoopcs9** [comment]
retest this please

**Comment by anoopcs9** [comment]
Hm..again failed at a weird point:

> Cloning into 'samba-build'...
> From https://github.com/gluster/samba-integration
>  *[new ref]         refs/pull/92/head -> pr_92
> Switched to branch 'pr_92'
> First, rewinding head to replay your work on top of it...
> Applying: Add LICENSE
> Using index info to reconstruct a base tree...
> Falling back to patching base and 3-way merge...
> No changes -- Patch already applied.
> Applying: Add README
> Using index info to reconstruct a base tree...
> Falling back to patching base and 3-way merge...
> Auto-merging README.md
> CONFLICT (add/add): Merge conflict in README.md
> Failed to merge in the changes.
> Patch failed at 0002 Add README
> The copy of the patch that failed is found in:
>    /root/samba-build/.git/rebase-apply/patch
> 
> When you have resolved this problem, run "git rebase --continue".
> If you prefer to skip this patch, run "git rebase --skip" instead.
> To check out the original branch and stop rebasing, run "git rebase --abort".

What does that mean? @obnoxxx any idea?

**Comment by anoopcs9** [comment]
> Hm..again failed at a weird point:
> 
> > Cloning into 'samba-build'...
> > From https://github.com/gluster/samba-integration
> > *[new ref]         refs/pull/92/head -> pr_92
> > Switched to branch 'pr_92'
> > First, rewinding head to replay your work on top of it...
> > Applying: Add LICENSE
> > Using index info to reconstruct a base tree...
> > Falling back to patching base and 3-way merge...
> > No changes -- Patch already applied.
> > Applying: Add README
> > Using index info to reconstruct a base tree...
> > Falling back to patching base and 3-way merge...
> > Auto-merging README.md
> > CONFLICT (add/add): Merge conflict in README.md
> > Failed to merge in the changes.
> > Patch failed at 0002 Add README
> > The copy of the patch that failed is found in:
> > /root/samba-build/.git/rebase-apply/patch
> > When you have resolved this problem, run "git rebase --continue".
> > If you prefer to skip this patch, run "git rebase --skip" instead.
> > To check out the original branch and stop rebasing, run "git rebase --abort".
> 
> What does that mean? @obnoxxx any idea?

I did a force push and error is no longer seen. May be I messed up with target branch last time..I don't know.

**Comment by obnoxxx** [comment]
@anoopcs9 - weird - now I hit the "update pr" button to merge in the changes of pr #91 which has just been merged, and the test fails again the same way as before... :thinking:

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
There might be a problem in https://github.com/gluster/centosci/blob/master/jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh - checking ...

**Comment by obnoxxx** [comment]
Might be related to the `--depth=1` cloning.
First enabling debugging in the script: https://github.com/gluster/centosci/pull/107

**Comment by obnoxxx** [comment]
It *is* related to the script. and probably `--depth=1` clone.
Please don't force-push yet.

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
This should fix it: https://github.com/gluster/centosci/pull/108

**Comment by obnoxxx** [comment]
retest this please

**Pull request merged**
