### PR TITLE
Don't enable the systemd smb service - ctdb manages Samba

### LINKED ISSUE #21: Fix enabling of smb service (systemd vs 50.samba)
The ctdb and Samba setup introduced in PR #20 left a few TODOs. Here is the dscription:

* first of all, we should not have both `50.samba` enabled and enabled the smb service in systemd. When `50.samba` is enabled, it takes over management of the smb service.
* Secondly, we should probably not enable 50.samba before we install and configure samba.

So I think the flow should be changed like this:

* In the role that sets up ctdb, `50.samba` should probably not be enabled (TODO: verify whether this is creating potential problems when enabled prematurely).
* In the role that sets up samba, the systemd smb service should **not** be enabled or started. Instead `50.samba` should be enabled and if needed we should use `ctdb event ...` to actually start the smb service with ctdb running (or just restart ctdb, but this should not be needed).

### PR DESCRIPTION
**Pull request by obnoxxx**
Fixes #21 

Signed-off-by: Michael Adam <obnox@samba.org>

### CODE REVIEW

**Comment by anoopcs9** [comment]
From #21 

- In the role that sets up ctdb, 50.samba should probably not be enabled (TODO: verify whether this is creating potential problems when enabled prematurely).
- In the role that sets up samba, the systemd smb service should not be enabled or started. Instead 50.samba should be enabled and if needed we should use ctdb event ... to actually start the smb service with ctdb running (or just restart ctdb, but this should not be needed).

So a complete fix would include moving the following section from `ctdb.setup` role to `samb-glusterfs.setup` role, right?
```
 - name: Enable samba management by ctdb
   command: '/bin/ctdb event script enable legacy 50.samba'
```

**Comment by obnoxxx** [comment]
@anoopcs9 writes:
> So a complete fix would include moving the following section from `ctdb.setup` role to `samba-glusterfs.setup` role, right?

Right that was the thinking, but I was unsure if it is really needed. So I tried. It seems like with this change, the system is working fine: Without needing to (re)start samba as part of the samba role, we get a working samba cluster at the end. So it may be fine...

**Comment by anoopcs9** [comment]
> @anoopcs9 writes:
> 
> > So a complete fix would include moving the following section from `ctdb.setup` role to `samba-glusterfs.setup` role, right?
> 
> Right that was the thinking, but I was unsure if it is really needed. So I tried. It seems like with this change, the system is working fine: Without needing to (re)start samba as part of the samba role, we get a working samba cluster at the end. So it may be fine...

Shall we then take this in?

lgtm

**Comment by spuiuk** [comment]
Tested this twice on my setup. Works fine.

**Pull request merged**
