### PR TITLE
smbtorture: Fix knownfail entry for `smb2.maximum_allowed`

### PR DESCRIPTION
**Pull request by anoopcs9**
See upstream [change](https://git.samba.org/?p=samba.git;a=commit;h=c73d666e5abe8717a5ea333a6dae3619d9621d48) for more details.

### CODE REVIEW

**Comment by anoopcs9** [comment]
retest this please

**Comment by spuiuk** [comment]
Anoop, The change is fine but the summary for the commit is a bit misleading. ie. In the upstream changelog, the maximum_allowed test is moved into it's own test suite and then entered into the known fail list.
While in our repo, we are simply adding the test to the known fail list.
So the patch title doesn't match what we are actually doing even though we are partially pull in bits of the patch with the same title. Would you consider changing the title of the commit?

**Comment by anoopcs9** [comment]
> Anoop, The change is fine but the summary for the commit is a bit misleading. ie. In the upstream changelog, the maximum_allowed test is moved into it's own test suite and then entered into the known fail list. While in our repo, we are simply adding the test to the known fail list. So the patch title doesn't match what we are actually doing even though we are partially pull in bits of the patch with the same title. Would you consider changing the title of the commit?

Done. But it seems like `smb2.deny` is failing only for distributed-disperse volumes. I'm onto it..

**Review by spuiuk — APPROVED** [review]
ACK.

The failures appear to be unconnected to this change and the change is required to fix the issue with the test failures.

**Pull request merged**
