### PR TITLE
add client

### PR DESCRIPTION
**Pull request by spuiuk**
This setups up the client and is based on my last two PRs. We do not run any test yet. I need to research the best way of running these tests.

### CODE REVIEW

**Comment by spuiuk** [comment]
Dependency failure installing vagrant on the host machine on doing the CI check.

**Comment by spuiuk** [comment]
Not sure how to trigger a CI run for this.

No changes to the master branch, so no case for rebasing and force pushing which would trigger a CI run.

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
this should trigger the ci re-run.
But any change to the branch would trigger a CI run too. So for example `git commit --amend` on the top commit and force-push should also do the trick ;-)

**Pull request merged**
